# Generated by Django 4.2.9 on 2026-02-14 23:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Establecimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subscription_status', models.CharField(choices=[('ACTIVE', 'Activa'), ('EXPIRED', 'Expirada'), ('SUSPENDED', 'Suspendida')], default='ACTIVE', max_length=20, verbose_name='Estado de Suscripción')),
                ('subscription_expiry', models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('license_key', models.CharField(max_length=100, unique=True, verbose_name='Clave de Licencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exportador', models.CharField(max_length=255, verbose_name='Exportador')),
                ('inspector_sag', models.CharField(max_length=255, verbose_name='Inspector SAG')),
                ('contraparte_sag', models.CharField(max_length=255, verbose_name='Contraparte SAG')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('especie', models.CharField(max_length=100, verbose_name='Especie')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='Número de Lote')),
                ('tamano_lote', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tamaño del Lote')),
                ('tipo_muestreo', models.CharField(choices=[('NORMAL', 'Normal'), ('POR_ETAPA', 'Por Etapa')], default='NORMAL', max_length=20, verbose_name='Tipo de Muestreo')),
                ('tipo_despacho', models.CharField(max_length=100, verbose_name='Tipo de Despacho')),
                ('cantidad_pallets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Pallets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.establishment', verbose_name='Planta/Establecimiento')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SamplingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_muestreo', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Porcentaje de Muestreo')),
                ('tamano_muestra', models.IntegerField(verbose_name='Tamaño de la Muestra')),
                ('cajas_seleccionadas', models.TextField(verbose_name='Cajas Seleccionadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_result', to='inspections.inspection', verbose_name='Inspección')),
            ],
            options={
                'verbose_name': 'Resultado de Muestreo',
                'verbose_name_plural': 'Resultados de Muestreo',
                'ordering': ['-created_at'],
            },
        ),
    ]
