# Generated by Django 4.2.9 on 2026-02-14 23:11

from django.db import migrations, models
import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='fecha',
            field=models.DateField(default=inspections.models.get_current_date, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='hora',
            field=models.TimeField(default=inspections.models.get_current_time, verbose_name='Hora'),
        ),
    ]
