# Generated by Django 4.2.9 on 2026-02-14 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0002_alter_inspection_fecha_alter_inspection_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_admin', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Administrador'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='subscription_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Suscripción'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ESTABLISHMENT_ADMIN', 'Administrador de Establecimiento'), ('INSPECTOR', 'Inspector')], default='INSPECTOR', max_length=30, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='EstablishmentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Formato hexadecimal: #RRGGBB', max_length=7, verbose_name='Color Primario')),
                ('secondary_color', models.CharField(default='#6b7280', help_text='Formato hexadecimal: #RRGGBB', max_length=7, verbose_name='Color Secundario')),
                ('accent_color', models.CharField(default='#10b981', help_text='Formato hexadecimal: #RRGGBB', max_length=7, verbose_name='Color de Acento')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo (Versión Oscura)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Favicon')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Empresa (Mostrar)')),
                ('welcome_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Bienvenida')),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto del Footer')),
                ('show_logo', models.BooleanField(default=True, verbose_name='Mostrar Logo')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='Modo Oscuro por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='inspections.establishment', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Tema de Establecimiento',
                'verbose_name_plural': 'Temas de Establecimientos',
            },
        ),
    ]
