# Generated by Django 4.2.9 on 2026-02-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_establishment_address_establishment_admin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='encargado_sag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Encargado Área SAG'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='exportadora',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Exportadora'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='planta_fruticola',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Planta Frutícola'),
        ),
    ]
