# Generated by Django 4.2.9 on 2026-02-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_establishment_encargado_sag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'ordering': ['planta_fruticola'], 'verbose_name': 'Establecimiento', 'verbose_name_plural': 'Establecimientos'},
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='name',
        ),
        migrations.AlterField(
            model_name='establishment',
            name='planta_fruticola',
            field=models.CharField(default='Sin nombre', max_length=255, verbose_name='Planta Frutícola'),
        ),
    ]
