# Generated by Django 4.2.9 on 2026-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_establishment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingresult',
            name='nombre_tabla',
            field=models.CharField(default='Hipergeométrica del 6%', max_length=100, verbose_name='Nombre de Tabla'),
        ),
        migrations.AddField(
            model_name='samplingresult',
            name='tipo_tabla',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Tabla'),
        ),
        migrations.AlterField(
            model_name='samplingresult',
            name='porcentaje_muestreo',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=5, null=True, verbose_name='Porcentaje de Muestreo'),
        ),
    ]
