# Generated by Django 4.2.9 on 2026-02-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_samplingresult_nombre_tabla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='boxes_per_pallet',
            field=models.JSONField(blank=True, default=list, help_text='Array con cantidad de cajas en cada pallet (solo para muestreo por etapa)', verbose_name='Cajas por Pallet'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='selected_pallets',
            field=models.JSONField(blank=True, default=list, help_text='Índices de pallets seleccionados para muestreo (solo para muestreo por etapa)', verbose_name='Pallets Seleccionados'),
        ),
    ]
