# Generated by Django 4.2.9 on 2026-02-15 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_inspection_boxes_per_pallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='altura_pallet',
            field=models.IntegerField(blank=True, help_text='Número de capas del pallet (altura)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Altura del Pallet'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='base_pallet',
            field=models.IntegerField(blank=True, help_text='Número de cajas por capa (base del pallet)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Base del Pallet'),
        ),
    ]
