# Generated by Django 4.2.9 on 2026-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_inspection_altura_pallet_inspection_base_pallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='altura_pallet',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='base_pallet',
        ),
        migrations.AddField(
            model_name='inspection',
            name='pallet_configurations',
            field=models.JSONField(blank=True, default=list, help_text='Array con configuración de cada pallet: [{numero_pallet, base, altura}, ...]', verbose_name='Configuraciones de Pallets'),
        ),
    ]
