# Generated by Django 4.2.9 on 2026-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_remove_inspection_altura_pallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingresult',
            name='incremento_aplicado',
            field=models.IntegerField(default=0, help_text='Incremento de intensidad: 0, 20 o 40', verbose_name='Incremento Aplicado (%)'),
        ),
        migrations.AddField(
            model_name='samplingresult',
            name='muestra_base',
            field=models.IntegerField(blank=True, help_text='Tamaño de muestra antes del incremento', null=True, verbose_name='Muestra Base'),
        ),
        migrations.AddField(
            model_name='samplingresult',
            name='muestra_final',
            field=models.IntegerField(blank=True, help_text='Tamaño de muestra después del incremento', null=True, verbose_name='Muestra Final'),
        ),
    ]
