# Generated by Django 4.2.9 on 2026-02-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='establishment',
            field=models.ForeignKey(blank=True, help_text='Establecimiento al que pertenece este usuario (para inspectores y admins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='inspections.establishment', verbose_name='Establecimiento Asignado'),
        ),
    ]
