# Generated by Django 4.2.9 on 2026-02-18 14:37

from django.db import migrations


def assign_establishments_to_profiles(apps, schema_editor):
    """
    Asignar establecimientos a los perfiles de usuarios existentes.
    - ESTABLISHMENT_ADMIN: asignar el establecimiento del que son admin
    """
    Establishment = apps.get_model('inspections', 'Establishment')
    UserProfile = apps.get_model('inspections', 'UserProfile')
    
    # Actualizar perfiles de admins de establecimiento
    establishments = Establishment.objects.all()
    for est in establishments:
        if est.admin_user:
            try:
                profile = UserProfile.objects.get(user=est.admin_user)
                if not profile.establishment:
                    profile.establishment = est
                    profile.save()
                    print(f"✅ Establecimiento asignado al perfil de {est.admin_user.username}")
            except UserProfile.DoesNotExist:
                print(f"⚠️ No existe perfil para {est.admin_user.username}")


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_userprofile_establishment'),
    ]

    operations = [
        migrations.RunPython(assign_establishments_to_profiles, migrations.RunPython.noop),
    ]
